project('mixere', 'cpp')

windows = import('windows')
cxx = meson.get_compiler('cpp')

audiere = dependency('audiere')
version = cxx.find_library('version')
htmlhelp = cxx.find_library('htmlhelp')

mixere_rc = windows.compile_resources('Mixere.rc', depend_files: ['res/app.manifest'])

executable(
    'mixere',
    [
        'AccelTable.cpp',
        'Audio.cpp',
        'AutoDlg.cpp',
        'AutoInfo.cpp',
        'AutoSliderCtrl.cpp',
        'AutoSliderDlg.cpp',
        'AutoSliderDlgBar.cpp',
        'AutoTriggerCtrl.cpp',
        'ChanAudio.cpp',
        'ChanInfo.cpp',
        'Channel.cpp',
        'ChildFrm.cpp',
        'ChildToolTip.cpp',
        'ClickSliderCtrl.cpp',
        'Clipboard.cpp',
        'ColorStatusBar.cpp',
        'ColumnResizer.cpp',
        'CrossfaderBar.cpp',
        'CtrlResize.cpp',
        'DialogBarEx.cpp',
        'DialogEx.cpp',
        'EditSnapsDlg.cpp',
        'FileSearchDlg.cpp',
        'FolderDialog.cpp',
        'FormListHeader.cpp',
        'FormListInfo.cpp',
        'FormListItemDlg.cpp',
        'FormListView.cpp',
        'HotKeyCtrlEx.cpp',
        'HotKeyList.cpp',
        'Hyperlink.cpp',
        'IconButton.cpp',
        'MSFadeBar.cpp',
        'MainFrm.cpp',
        'MissingFilesDlg.cpp',
        'MixerInfo.cpp',
        'Mixere.cpp',
        'MixereDoc.cpp',
        'MixereView.cpp',
        'MultiAutoDlg.cpp',
        'MultiMix.cpp',
        'NumEdit.cpp',
        'OptionsDlg.cpp',
        'OptsAppearDlg.cpp',
        'OptsGeneralDlg.cpp',
        'OptsSlidersDlg.cpp',
        'Persist.cpp',
        'PopupEdit.cpp',
        'PropertiesDlg.cpp',
        'ReplaceFilesDlg.cpp',
        'SelectSliderCtrl.cpp',
        'SmartBuf.cpp',
        'Snapshot.cpp',
        'SnapshotBar.cpp',
        'StaticEdit.cpp',
        'StdAfx.cpp',
        'SubFileFind.cpp',
        'TakeSnapDlg.cpp',
        'TempoBar.cpp',
        'TimeEdit.cpp',
        'UndoManager.cpp',
        'UndoState.cpp',
        'Undoable.cpp',
        'VersionInfo.cpp',
        'VolumeBar.cpp',
        'Win32Console.cpp',
    ],
    mixere_rc,
    cpp_args: [
        '-D_AFXDLL',
        '-DWINVER=_WIN32_WINNT_WIN10',
        '-D_WIN32_WINNT=_WIN32_WINNT_WIN10',
        '-DNTDDI_VERSION=NTDDI_WIN10_19H1',
    ],
    dependencies: [audiere, version, htmlhelp],
    win_subsystem: 'windows',
    install: true,
)
