//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Mixere.rc
//
#define IDR_MAINFRAME                   101
#define IDR_AUTO_DLG                    102
#define IDR_AUTO_SLIDER                 103
#define IDR_MIXERETYPE                  104
#define IDR_MULTI_AUTO_DLG              105
#define IDR_POPUP                       106
#define IDB_SORTD                       107
#define IDB_SORTU                       108
#define IDI_CFDIPLESS                   109
#define IDI_CFLINEAR                    110
#define IDI_LOOPD                       111
#define IDI_LOOPU                       112
#define IDI_MINUTESD                    113
#define IDI_MINUTESU                    114
#define IDI_MUTED                       115
#define IDI_MUTEU                       116
#define IDI_PAUSED                      117
#define IDI_PAUSEU                      118
#define IDI_PLAYD                       119
#define IDI_PLAYU                       120
#define IDI_SOLOD                       121
#define IDI_SOLOU                       122
#define IDI_STAGGER                     123
#define IDI_STOPD                       124
#define IDI_STOPU                       125
#define IDD_ABOUTBOX                    126
#define IDD_AUTO_DLG                    127
#define IDD_CHANNEL                     128
#define IDD_CROSSFADER_BAR              129
#define IDD_EDIT_SNAPS_DLG              130
#define IDD_FILE_SEARCH_DLG             131
#define IDD_FORMLIST_FORM               132
#define IDD_MISSING_FILES_DLG           133
#define IDD_MS_FADE_BAR                 134
#define IDD_MULTI_AUTO_DLG              135
#define IDD_OPTS_APPEAR_DLG             136
#define IDD_OPTS_GENERAL_DLG            137
#define IDD_OPTS_SLIDERS_DLG            138
#define IDD_PROPERTIES_DLG              139
#define IDD_REPLACE_FILES_DLG           140
#define IDD_SNAPSHOT_BAR                141
#define IDD_TAKE_SNAP_DLG               142
#define IDD_TEMPO_BAR                   143
#define IDD_VOLUME_BAR                  144
#define IDS_APP_ABOUT_LICENSE           200
#define IDS_APP_ABOUT_TEXT              201
#define IDS_AUTO                        202
#define IDS_AUTO_DIALOG                 203
#define IDS_AUTO_QUICK_START            204
#define IDS_AUTO_SELECTION              205
#define IDS_AUTO_TIME_EDIT              206
#define IDS_AUTO_TRANSPORT              207
#define IDS_AUTO_WAVEFORM               208
#define IDS_AUTO_WAVE_RAMP_DOWN         209
#define IDS_AUTO_WAVE_RAMP_UP           210
#define IDS_AUTO_WAVE_RANDOM            211
#define IDS_AUTO_WAVE_SQUARE            212
#define IDS_AUTO_WAVE_TRIANGLE          213
#define IDS_BAD_FILE_FORMAT             214
#define IDS_CANT_CREATE_VIEW            215
#define IDS_CANT_FIND_STRING            216
#define IDS_CANT_LOAD_AUDIO             217
#define IDS_CANT_SET_AUDIO_DEV          218
#define IDS_CH_LOOP                     219
#define IDS_CH_MUTE                     220
#define IDS_CH_MUTE_SOLO                221
#define IDS_CH_NAME                     222
#define IDS_CH_NUMBER                   223
#define IDS_CH_PAN                      224
#define IDS_CH_PAUSE                    225
#define IDS_CH_PITCH                    226
#define IDS_CH_PLAY                     227
#define IDS_CH_POSITION                 228
#define IDS_CH_SOLO                     229
#define IDS_CH_STOP                     230
#define IDS_CH_TRANSPORT                231
#define IDS_CH_TRIGGER                  232
#define IDS_CH_VOLUME                   233
#define IDS_CROSSFADER                  234
#define IDS_CROSSFADER_CAPTION          235
#define IDS_EDIT_TEMPO                  236
#define IDS_FADER                       237
#define IDS_FILE_DIALOG_ERROR           238
#define IDS_FLU_COLUMN_WIDTH            239
#define IDS_FLU_CUT                     240
#define IDS_FLU_DELETE                  241
#define IDS_FLU_DRAG                    242
#define IDS_FLU_INSERT                  243
#define IDS_FLU_LOWER_ITEM_COUNT        244
#define IDS_FLU_PASTE                   245
#define IDS_FLU_RAISE_ITEM_COUNT        246
#define IDS_FLU_SELECT                  247
#define IDS_FLU_SORT                    248
#define IDS_FL_CANT_INSERT_ITEM         249
#define IDS_FL_EDIT_REDO_FMT            250
#define IDS_FL_EDIT_UNDO_FMT            251
#define IDS_HELP_FILE_MISSING           252
#define IDS_HLINK_CANT_LAUNCH           253
#define IDS_LOAD_AUDIO                  254
#define IDS_MASTER                      255
#define IDS_MASTER_VOLUME               256
#define IDS_MS_FADE_BAR                 257
#define IDS_MS_FADE_CAPTION             258
#define IDS_MS_FADE_EDIT                259
#define IDS_MS_FADE_SLIDER              260
#define IDS_MU_EDIT_AUTO                261
#define IDS_MU_END_SOLO                 262
#define IDS_MU_GO                       263
#define IDS_MU_INSERT_AUDIO             264
#define IDS_MU_KEEP_SOLO                265
#define IDS_MU_LOAD_AUDIO               266
#define IDS_MU_LOOP                     267
#define IDS_MU_MUTE                     268
#define IDS_MU_SET_DEFAULTS             269
#define IDS_MU_SHOW_MS_FADE             270
#define IDS_MU_SHOW_SNAPSHOT            271
#define IDS_MU_SHOW_TEMPO               272
#define IDS_MU_SHOW_VOLUME              273
#define IDS_MU_SOLO                     274
#define IDS_MU_TRANSPORT                275
#define IDS_NO_INPUT                    276
#define IDS_OPTIONS                     277
#define IDS_SELECTED_CHANS              278
#define IDS_SELECTION                   279
#define IDS_SNAPSHOT_BAR                280
#define IDS_SNAPSHOT_CAPTION            281
#define IDS_SNAP_DEFAULT_TITLE          282
#define IDS_SNAP_RT_EXACT               283
#define IDS_SNAP_RT_SMOOTH              284
#define IDS_SNAP_SORT_CREATED           285
#define IDS_SNAP_SORT_TITLE             286
#define IDS_SSK_ASSIGNED                287
#define IDS_SSK_RSVD_CMD                288
#define IDS_SSK_RSVD_MENU               289
#define IDS_SSK_RSVD_SYSTEM             290
#define IDS_SSU_DELETE                  291
#define IDS_SSU_HOTKEY                  292
#define IDS_SSU_OPTIONS                 293
#define IDS_SSU_RENAME                  294
#define IDS_SSU_RESTORE                 295
#define IDS_SSU_TAKE                    296
#define IDS_STATIC_EDIT_TEXT            297
#define IDS_TEMPO_BAR                   298
#define IDS_UNDO_CANT_CANCEL_EDIT       299
#define IDS_UNDO_CANT_FIND_INSTANCE     300
#define IDS_UNDO_IGNORING_NOTIFY        301
#define IDS_UNDO_TREE_TOO_DEEP          302
#define IDS_VOLUME_BAR                  303
#define IDC_ABOUT_TEXT                  1001
#define IDC_ABOUT_URL                   1002
#define IDC_ANIM_SPEED                  1003
#define IDC_ANIM_SPEED_MAX              1004
#define IDC_ANIM_SPEED_MIN              1005
#define IDC_AUDIO_DEVICE                1006
#define IDC_AUTO_END_EDIT               1007
#define IDC_AUTO_END_SPIN               1008
#define IDC_AUTO_LOOP                   1009
#define IDC_AUTO_MIDDLE_CLICK           1010
#define IDC_AUTO_MINUTES                1011
#define IDC_AUTO_PAUSE                  1012
#define IDC_AUTO_PLAY                   1013
#define IDC_AUTO_POS_EDIT               1014
#define IDC_AUTO_POS_SPIN               1015
#define IDC_AUTO_SLIDER                 1016
#define IDC_AUTO_STAGGER                1017
#define IDC_AUTO_START_EDIT             1018
#define IDC_AUTO_START_SPIN             1019
#define IDC_AUTO_STOP                   1020
#define IDC_AUTO_TIME_EDIT              1021
#define IDC_AUTO_TIME_POS               1022
#define IDC_AUTO_TIME_SPIN              1023
#define IDC_AUTO_TRIG_LOOP_OFF          1024
#define IDC_AUTO_VOL_UNPAUSE            1025
#define IDC_AUTO_WAVEFORM               1026
#define IDC_BPM_EDIT                    1027
#define IDC_BPM_SPIN                    1028
#define IDC_BROWSE                      1029
#define IDC_CHANNEL_COUNT               1030
#define IDC_CHOOSE_COLOR                1031
#define IDC_CHOOSE_FONT                 1032
#define IDC_CH_LOOP                     1033
#define IDC_CH_MUTE                     1034
#define IDC_CH_NAME                     1035
#define IDC_CH_NUMBER                   1036
#define IDC_CH_PAN                      1037
#define IDC_CH_PAUSE                    1038
#define IDC_CH_PITCH                    1039
#define IDC_CH_PLAY                     1040
#define IDC_CH_POS                      1041
#define IDC_CH_SOLO                     1042
#define IDC_CH_STOP                     1043
#define IDC_CH_VOL                      1044
#define IDC_COLOR_LIST                  1045
#define IDC_COLOR_SAMPLE                1046
#define IDC_DEFAULT_FONT                1047
#define IDC_DISPLAY_TOOLTIPS            1048
#define IDC_DRAG_MULTI                  1049
#define IDC_DRAG_SINGLE                 1050
#define IDC_FADER_TYPE                  1051
#define IDC_FONT_SAMPLE                 1052
#define IDC_HAND                        1053
#define IDC_LICENSE                     1054
#define IDC_LIST                        1055
#define IDC_MS_FADE_EDIT                1056
#define IDC_MS_FADE_MINUTES             1057
#define IDC_MS_FADE_SLIDER              1058
#define IDC_MS_FADE_SPIN                1059
#define IDC_OPENDLG                     1060
#define IDC_PROCEED                     1061
#define IDC_SEARCH_ALL                  1062
#define IDC_SEARCH_FOLDER               1063
#define IDC_SNAPSHOT_COMBO              1064
#define IDC_SNAP_DELETE                 1065
#define IDC_SNAP_EXACT                  1066
#define IDC_SNAP_HOTKEY                 1067
#define IDC_SNAP_LIST                   1068
#define IDC_SNAP_NAME_EDIT              1069
#define IDC_SNAP_RENAME                 1070
#define IDC_SNAP_RESTORE                1071
#define IDC_SNAP_SMOOTH                 1072
#define IDC_SNAP_SORT                   1073
#define IDC_SOURCE_A                    1074
#define IDC_SOURCE_B                    1075
#define IDC_STATUS                      1076
#define IDC_UNDO_LEVELS                 1077
#define IDC_UNDO_UNLIMITED              1078
#define ID_AUTO_PAN                     32771
#define ID_AUTO_PAUSE                   32772
#define ID_AUTO_PITCH                   32773
#define ID_AUTO_PLAY                    32774
#define ID_AUTO_POS                     32775
#define ID_AUTO_STOP                    32776
#define ID_AUTO_TOGGLE_LOOP             32777
#define ID_AUTO_TOGGLE_MINUTES          32778
#define ID_AUTO_TOGGLE_PLAY             32779
#define ID_AUTO_VOLUME                  32780
#define ID_CONTEXT_COPY                 32781
#define ID_CONTEXT_CUT                  32782
#define ID_CONTEXT_DELETE               32783
#define ID_CONTEXT_INSERT               32784
#define ID_CROSSFADER                   32785
#define ID_EDIT_DELETE                  32786
#define ID_EDIT_DESELECT                32787
#define ID_EDIT_INSERT                  32788
#define ID_EDIT_NAME                    32789
#define ID_EDIT_SNAPSHOTS               32790
#define ID_END_SOLO                     32791
#define ID_FILE_PROPERTIES              32792
#define ID_GO                           32793
#define ID_HOME_PAGE                    32794
#define ID_INDICATOR_MUTE               32795
#define ID_INDICATOR_SOLO               32796
#define ID_KEEP_SOLO                    32797
#define ID_LOAD_AUDIO                   32798
#define ID_MIXER_TEMPO                  32799
#define ID_MIXER_VOLUME                 32800
#define ID_MS_FADE                      32801
#define ID_PAUSE                        32802
#define ID_PLAY                         32803
#define ID_SET_DEFAULTS                 32804
#define ID_SNAPSHOTS                    32805
#define ID_STOP                         32806
#define ID_TAKE_SNAPSHOT                32807
#define ID_TOGGLE_AUTO_DLG              32808
#define ID_TOGGLE_LOOP                  32809
#define ID_TOGGLE_MUTE                  32810
#define ID_TOGGLE_PLAY                  32811
#define ID_TOGGLE_SOLO                  32812
#define ID_TOOLS_MASTERVOL              32813
#define ID_TOOLS_OPTIONS                32814

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                1
#define _APS_NEXT_RESOURCE_VALUE        304
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
