name: VS2022
on:
  - push
  - pull_request

jobs:
  VS2022-Build-x86:
    runs-on: windows-2022
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Build
        shell: cmd
        run: |
          msbuild ./Mixere.sln /m /p:Configuration=Release,Platform=Win32
          mkdir .\output
          move .\Release\Mixere.exe .\output\Mixere.exe
          move .\Release\Audiere.dll .\output\Audiere.dll
      - name: Display SHA-256
        run: |
          sha256sum ./output/Mixere.exe
          sha256sum ./output/Audiere.dll
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name == 'push' }}
        with:
          name: VS2022-win32
          path: ./output/
  VS2022-Build-x64:
    runs-on: windows-2022
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Build
        shell: cmd
        run: |
          msbuild ./Mixere.sln /m /p:Configuration=Release,Platform=x64
          mkdir .\output
          move .\x64\Release\Mixere.exe .\output\Mixere.exe
          move .\x64\Release\Audiere.dll .\output\Audiere.dll
      - name: Display SHA-256
        run: |
          sha256sum ./output/Mixere.exe
          sha256sum ./output/Audiere.dll
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name == 'push' }}
        with:
          name: VS2022-win64
          path: ./output/
